/*
 * This file was automatically generated by EvoSuite
 * Tue Jan 16 19:35:19 GMT 2024
 */


import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class VCardBean_ESTest extends VCardBean_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      VCardBean vCardBean0 = new VCardBean();
      vCardBean0.setVCard("BEGIN:VCARD\nFN:BEGIN:VCARDBEGIN:VCARD\nFN:, ,\nN:,;;,;\nTITLE:,\nORG:,\nEMAIL;TYPE=INTERNET:,\nTEL;TYPE=FAX:4ODFH$\nEND:VCARD ,\nN:,;;BEGIN:VCARDBEGIN:VCARD\nFN:, ,\nN:,;;,;\nTITLE:,\nORG:,\nEMAIL;TYPE=INTERNET:,\nTEL;TYPE=FAX:4ODFH$\nEND:VCARD;\nTITLE:,\nORG:,\nEMAIL;TYPE=INTERNET:,\nTEL;TYPE=VOICE:V.nLH4]i\nTEL;TYPE=FAX:4OdfH$\nEND:VCARD");
      assertEquals(",", vCardBean0.getTitle());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      VCardBean vCardBean0 = new VCardBean();
      vCardBean0.setVCard("BEGIN:VCARD\nFN:\n BEGIN:VCARDEND:VCARD BEGIN:VCARDEND:VCARD\nN:BEGIN:VCARDEND:VCARD;BEGIN:VCARDEND:VCARD;\n;\nORG:BEGIN:VCARDEND:VCARD\nEMAIL;TYPE=INTERNET:BEGIN:VCARDEND:VCARD\nEND:VCARD");
      assertNull(vCardBean0.getLastName());
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      VCardBean vCardBean0 = new VCardBean();
      vCardBean0.setFax("4OdfH$");
      vCardBean0.setFirstName(",");
      vCardBean0.setLastName(",");
      vCardBean0.setOrganization(",");
      vCardBean0.setEmail(",");
      String string0 = vCardBean0.toString();
      assertNotNull(string0);
      assertEquals("BEGIN:VCARD\nFN:, ,\nN:,;;,;\nORG:,\nEMAIL;TYPE=INTERNET:,\nTEL;TYPE=FAX:4OdfH$\nEND:VCARD", string0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      VCardBean vCardBean0 = new VCardBean();
      vCardBean0.setPhone("V.nLH4]i");
      vCardBean0.setFirstName(",");
      vCardBean0.setLastName(",");
      vCardBean0.setOrganization(",");
      vCardBean0.setEmail(",");
      String string0 = vCardBean0.toString();
      assertNotNull(string0);
      assertEquals("BEGIN:VCARD\nFN:, ,\nN:,;;,;\nORG:,\nEMAIL;TYPE=INTERNET:,\nTEL;TYPE=VOICE:V.nLH4]i\nEND:VCARD", string0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      VCardBean vCardBean0 = new VCardBean();
      vCardBean0.setFirstName(",");
      vCardBean0.setTitle(",");
      vCardBean0.setLastName(",");
      vCardBean0.setOrganization(",");
      vCardBean0.setEmail(",");
      String string0 = vCardBean0.toString();
      assertNotNull(string0);
      assertEquals("BEGIN:VCARD\nFN:, ,\nN:,;;,;\nTITLE:,\nORG:,\nEMAIL;TYPE=INTERNET:,\nEND:VCARD", string0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      VCardBean vCardBean0 = new VCardBean();
      vCardBean0.setFirstName("\n");
      vCardBean0.setLastName("BEGIN:VCARDEND:VCARD");
      vCardBean0.setOrganization("BEGIN:VCARDEND:VCARD");
      vCardBean0.setEmail("BEGIN:VCARDEND:VCARD");
      vCardBean0.setMiddleName("BEGIN:VCARDEND:VCARD");
      String string0 = vCardBean0.toString();
      assertNotNull(string0);
      assertEquals("BEGIN:VCARD\nFN:\n BEGIN:VCARDEND:VCARD BEGIN:VCARDEND:VCARD\nN:BEGIN:VCARDEND:VCARD;BEGIN:VCARDEND:VCARD;\n;\nORG:BEGIN:VCARDEND:VCARD\nEMAIL;TYPE=INTERNET:BEGIN:VCARDEND:VCARD\nEND:VCARD", string0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      VCardBean vCardBean0 = new VCardBean();
      vCardBean0.setFirstName("tel");
      vCardBean0.setLastName("tel");
      vCardBean0.setOrganization("tel");
      vCardBean0.setEmail("tel");
      vCardBean0.setFormattedName("tel");
      String string0 = vCardBean0.getVCard();
      assertEquals("BEGIN:VCARD\nFN:tel\nN:tel;;tel;\nORG:tel\nEMAIL;TYPE=INTERNET:tel\nEND:VCARD", string0);
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      VCardBean vCardBean0 = new VCardBean();
      String string0 = vCardBean0.toString();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      VCardBean vCardBean0 = new VCardBean();
      vCardBean0.setVCard("TEL;TYPE=FAX:");
      String string0 = vCardBean0.toString();
      assertEquals("TEL;TYPE=FAX:", string0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      VCardBean vCardBean0 = new VCardBean();
      vCardBean0.setVCard("");
      String string0 = vCardBean0.toString();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      VCardBean vCardBean0 = new VCardBean();
      vCardBean0.setVCard("BEGIN:VCARD\n");
      boolean boolean0 = vCardBean0.isValidVCard();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      VCardBean vCardBean0 = new VCardBean();
      boolean boolean0 = vCardBean0.isValidVCard();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      VCardBean vCardBean0 = new VCardBean();
      String string0 = vCardBean0.getVCard();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      VCardBean vCardBean0 = new VCardBean();
      vCardBean0.setVCard("");
      String string0 = vCardBean0.getVCard();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      VCardBean vCardBean0 = new VCardBean();
      String string0 = vCardBean0.getTitle();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      VCardBean vCardBean0 = new VCardBean();
      vCardBean0.setTitle("#p6gn\"pegXIw89");
      String string0 = vCardBean0.getTitle();
      assertEquals("#p6gn\"pegXIw89", string0);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      VCardBean vCardBean0 = new VCardBean();
      vCardBean0.setTitle("");
      String string0 = vCardBean0.getTitle();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      VCardBean vCardBean0 = new VCardBean();
      String string0 = vCardBean0.getPhone();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      VCardBean vCardBean0 = new VCardBean();
      vCardBean0.setPhone("BEGIN:VCARD\n");
      String string0 = vCardBean0.getPhone();
      assertEquals("BEGIN:VCARD\n", string0);
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      VCardBean vCardBean0 = new VCardBean();
      vCardBean0.setPhone("");
      String string0 = vCardBean0.getPhone();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      VCardBean vCardBean0 = new VCardBean();
      String string0 = vCardBean0.getOrganization();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      VCardBean vCardBean0 = new VCardBean();
      vCardBean0.setOrganization("xM4Yr4V_|lX");
      String string0 = vCardBean0.getOrganization();
      assertEquals("xM4Yr4V_|lX", string0);
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      VCardBean vCardBean0 = new VCardBean();
      vCardBean0.setOrganization("");
      String string0 = vCardBean0.getOrganization();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      VCardBean vCardBean0 = new VCardBean();
      String string0 = vCardBean0.getMiddleName();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      VCardBean vCardBean0 = new VCardBean();
      vCardBean0.setMiddleName("M>d3x;!pD `tmp6O'q");
      String string0 = vCardBean0.getMiddleName();
      assertEquals("M>d3x;!pD `tmp6O'q", string0);
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      VCardBean vCardBean0 = new VCardBean();
      vCardBean0.setMiddleName("");
      String string0 = vCardBean0.getMiddleName();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      VCardBean vCardBean0 = new VCardBean();
      String string0 = vCardBean0.getLastName();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      VCardBean vCardBean0 = new VCardBean();
      vCardBean0.setLastName("VAg");
      String string0 = vCardBean0.getLastName();
      assertEquals("VAg", string0);
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      VCardBean vCardBean0 = new VCardBean();
      vCardBean0.setLastName("");
      String string0 = vCardBean0.getLastName();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      VCardBean vCardBean0 = new VCardBean();
      String string0 = vCardBean0.getFormattedName();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      VCardBean vCardBean0 = new VCardBean();
      vCardBean0.setFormattedName(",");
      String string0 = vCardBean0.getFormattedName();
      assertEquals(",", string0);
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      VCardBean vCardBean0 = new VCardBean();
      vCardBean0.setFormattedName("");
      String string0 = vCardBean0.getFormattedName();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      VCardBean vCardBean0 = new VCardBean();
      String string0 = vCardBean0.getFirstName();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      VCardBean vCardBean0 = new VCardBean();
      vCardBean0.setFirstName("VGEqY9+");
      String string0 = vCardBean0.getFirstName();
      assertEquals("VGEqY9+", string0);
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      VCardBean vCardBean0 = new VCardBean();
      vCardBean0.setFirstName("");
      String string0 = vCardBean0.getFirstName();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      VCardBean vCardBean0 = new VCardBean();
      String string0 = vCardBean0.getFax();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      VCardBean vCardBean0 = new VCardBean();
      vCardBean0.setFax("&");
      String string0 = vCardBean0.getFax();
      assertEquals("&", string0);
  }

  @Test(timeout = 4000)
  public void test37()  throws Throwable  {
      VCardBean vCardBean0 = new VCardBean();
      vCardBean0.setFax("");
      String string0 = vCardBean0.getFax();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test38()  throws Throwable  {
      VCardBean vCardBean0 = new VCardBean();
      String string0 = vCardBean0.getEmail();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test39()  throws Throwable  {
      VCardBean vCardBean0 = new VCardBean();
      vCardBean0.setEmail("'uJ\"w>vl3'`?");
      String string0 = vCardBean0.getEmail();
      assertEquals("'uJ\"w>vl3'`?", string0);
  }

  @Test(timeout = 4000)
  public void test40()  throws Throwable  {
      VCardBean vCardBean0 = new VCardBean();
      vCardBean0.setEmail("");
      String string0 = vCardBean0.getEmail();
      assertEquals("", string0);
  }
}
