/*
 * This file was automatically generated by EvoSuite
 * Tue Jan 16 19:38:57 GMT 2024
 */


import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class VCardBean_ESTest extends VCardBean_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      VCardBean vCardBean0 = new VCardBean();
      vCardBean0.setVCard("5@|2S}22pWM1a8qdh7=");
      boolean boolean0 = vCardBean0.isValidVCard();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      VCardBean vCardBean0 = new VCardBean();
      boolean boolean0 = vCardBean0.isValidVCard();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      VCardBean vCardBean0 = new VCardBean();
      vCardBean0.setVCard("BEGIN:VCARD\nFN: \nN:;;;\nTITLE:\nORG:\nEMAIL;TYPE=INTERNET:JPP6YX)[WUT\nEND:VCARD");
      assertEquals("", vCardBean0.getFormattedName());
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      VCardBean vCardBean0 = new VCardBean();
      vCardBean0.setVCard("BEGIN:VCARDBEGIN:VCARD\nFN:S-?5XC S-?5XC S-?5XC\nN:S-?5XC;S-?5XC;S-?5XC;\nTITLE:S-?5XC\nORG:S-?5XC\nEMAIL;TYPE=INTERNET:JPP6YX)UT\nTEL;TYPE=VOICE:S-?5XC\nEND:VCARD");
      assertNull(vCardBean0.getTitle());
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      VCardBean vCardBean0 = new VCardBean();
      vCardBean0.setVCard("BEGIN:VCARD\nFN:S-?5xc S-?5xc\nN:S-?5xc;;S-?5xc;\nORG:BEGIN:VCARDBEGIN:VCARD\nFN:S-?5XC S-?5XC S-?5XC\nN:S-?5XC;S-?5XC;S-?5XC;\nTITLE:S-?5XC\nORG:S-?5XC\nEMAIL;TYPE=INTERNET:\nTLL;TYPE=VOICE:BTGIN:VCARDBEGIN:VCARD\nFN:S-?5XC S-?5XC S-?5XC\nN:S-?5XC;S-?5XC;S-?5XC;\nTITLE:S-?5XC\nORGS?5XC\nEMAIL;TYPE=INTERNET:S-?5XC\nTEL;TYPE=FAX:S-?5XC\nEND:VCARD\nTEL;TYPE=FAX:S-?5XC\nEND:VCARD\nEMAIL;TYPE=INTERNET:JPP6YX)[WUT\nEND:VCARD");
      assertNull(vCardBean0.getFax());
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      VCardBean vCardBean0 = new VCardBean();
      vCardBean0.setFirstName("BEGIN:VCARDBEGIN:VCARD\nFN:S-?5XC S-?5XC S-?5XC\nN:S-?5XC;S-?5XC;S-?5XC;\nTITLE:S-?5XC\nORG:S-?5XC\nEMAIL;TYPE=INTERNET:JPP6YX)UT\nTEL;TYPE=VOICE:S-?5XC\nEND:VCARD");
      vCardBean0.setLastName("BEGIN:VCARDBEGIN:VCARD\nFN:S-?5XC S-?5XC S-?5XC\nN:S-?5XC;S-?5XC;S-?5XC;\nTITLE:S-?5XC\nORG:S-?5XC\nEMAIL;TYPE=INTERNET:JPP6YX)UT\nTEL;TYPE=VOICE:S-?5XC\nEND:VCARD");
      vCardBean0.setEmail("BEGIN:VCARDBEGIN:VCARD\nFN:S-?5XC S-?5XC S-?5XC\nN:S-?5XC;S-?5XC;S-?5XC;\nTITLE:S-?5XC\nORG:S-?5XC\nEMAIL;TYPE=INTERNET:JPP6YX)UT\nTEL;TYPE=VOICE:S-?5XC\nEND:VCARD");
      vCardBean0.setOrganization("BEGIN:VCARDBEGIN:VCARD\nFN:S-?5XC S-?5XC S-?5XC\nN:S-?5XC;S-?5XC;S-?5XC;\nTITLE:S-?5XC\nORG:S-?5XC\nEMAIL;TYPE=INTERNET:JPP6YX)UT\nTEL;TYPE=VOICE:S-?5XC\nEND:VCARD");
      String string0 = vCardBean0.getVCard();
      vCardBean0.setVCard(string0);
      assertEquals("JPP6YX)UT", vCardBean0.getEmail());
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      VCardBean vCardBean0 = new VCardBean();
      vCardBean0.setVCard((String) null);
      assertNull(vCardBean0.getOrganization());
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      VCardBean vCardBean0 = new VCardBean();
      vCardBean0.setFirstName("S-?5xc");
      vCardBean0.setLastName("S-?5xc");
      vCardBean0.setOrganization("S-?5xc");
      vCardBean0.setFax("");
      vCardBean0.setEmail("S-?5xc");
      String string0 = vCardBean0.getVCard();
      assertNotNull(string0);
      assertEquals("BEGIN:VCARD\nFN:S-?5xc S-?5xc\nN:S-?5xc;;S-?5xc;\nORG:S-?5xc\nEMAIL;TYPE=INTERNET:S-?5xc\nEND:VCARD", string0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      VCardBean vCardBean0 = new VCardBean();
      vCardBean0.setEmail("S-?5xc");
      vCardBean0.setFirstName("S-?5xc");
      vCardBean0.setLastName("S-?5xc");
      vCardBean0.setFax("S-?5xc");
      vCardBean0.setOrganization("S-?5xc");
      String string0 = vCardBean0.getVCard();
      assertEquals("BEGIN:VCARD\nFN:S-?5xc S-?5xc\nN:S-?5xc;;S-?5xc;\nORG:S-?5xc\nEMAIL;TYPE=INTERNET:S-?5xc\nTEL;TYPE=FAX:S-?5xc\nEND:VCARD", string0);
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      VCardBean vCardBean0 = new VCardBean();
      vCardBean0.setFirstName("");
      vCardBean0.setLastName("");
      vCardBean0.setOrganization("");
      vCardBean0.setEmail("JPP6YX)[WUT");
      vCardBean0.setPhone("");
      String string0 = vCardBean0.toString();
      assertEquals("BEGIN:VCARD\nFN: \nN:;;;\nORG:\nEMAIL;TYPE=INTERNET:JPP6YX)[WUT\nEND:VCARD", string0);
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      VCardBean vCardBean0 = new VCardBean();
      vCardBean0.setEmail("S-?5xc");
      vCardBean0.setFirstName("S-?5xc");
      vCardBean0.setLastName("S-?5xc");
      vCardBean0.setOrganization("S-?5xc");
      vCardBean0.setPhone("S-?5xc");
      String string0 = vCardBean0.getVCard();
      assertNotNull(string0);
      assertEquals("BEGIN:VCARD\nFN:S-?5xc S-?5xc\nN:S-?5xc;;S-?5xc;\nORG:S-?5xc\nEMAIL;TYPE=INTERNET:S-?5xc\nTEL;TYPE=VOICE:S-?5xc\nEND:VCARD", string0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      VCardBean vCardBean0 = new VCardBean();
      vCardBean0.setEmail("S-?5xc");
      vCardBean0.setFirstName("S-?5xc");
      vCardBean0.setLastName("S-?5xc");
      vCardBean0.setOrganization("S-?5xc");
      vCardBean0.setTitle("S-?5xc");
      String string0 = vCardBean0.getVCard();
      assertNotNull(string0);
      assertEquals("BEGIN:VCARD\nFN:S-?5xc S-?5xc\nN:S-?5xc;;S-?5xc;\nTITLE:S-?5xc\nORG:S-?5xc\nEMAIL;TYPE=INTERNET:S-?5xc\nEND:VCARD", string0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      VCardBean vCardBean0 = new VCardBean();
      vCardBean0.setFirstName("");
      vCardBean0.setEmail("");
      vCardBean0.setLastName("^}QN");
      vCardBean0.setOrganization("QFJN,P*WREZ");
      vCardBean0.setMiddleName("");
      String string0 = vCardBean0.toString();
      assertNotNull(string0);
      assertEquals("BEGIN:VCARD\nFN: ^}QN\nN:^}QN;;;\nORG:QFJN,P*WREZ\nEMAIL;TYPE=INTERNET:\nEND:VCARD", string0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      VCardBean vCardBean0 = new VCardBean();
      vCardBean0.setMiddleName(" bmr>VF");
      vCardBean0.setFirstName("Wzc]&(I#$j]<C0<+c4");
      vCardBean0.setEmail("");
      vCardBean0.setOrganization("Wzc]&(I#$j]<C0<+c4");
      vCardBean0.setLastName("^}QN");
      String string0 = vCardBean0.getVCard();
      assertEquals("BEGIN:VCARD\nFN:Wzc]&(I#$j]<C0<+c4  bmr>VF ^}QN\nN:^}QN; bmr>VF;Wzc]&(I#$j]<C0<+c4;\nORG:Wzc]&(I#$j]<C0<+c4\nEMAIL;TYPE=INTERNET:\nEND:VCARD", string0);
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      VCardBean vCardBean0 = new VCardBean();
      vCardBean0.setFirstName(";");
      vCardBean0.setFormattedName("");
      vCardBean0.setEmail(";");
      vCardBean0.setLastName(";");
      vCardBean0.setOrganization(";");
      String string0 = vCardBean0.getVCard();
      assertNotNull(string0);
      assertEquals("BEGIN:VCARD\nFN:\nN:;;;;;\nORG:;\nEMAIL;TYPE=INTERNET:;\nEND:VCARD", string0);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      VCardBean vCardBean0 = new VCardBean();
      vCardBean0.setEmail("t=;XZZj/+!8/9Ix@)");
      vCardBean0.setFirstName("");
      vCardBean0.setLastName("");
      String string0 = vCardBean0.toString();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      VCardBean vCardBean0 = new VCardBean();
      vCardBean0.setFirstName("S-?5xc");
      vCardBean0.setLastName("S-?5xc");
      String string0 = vCardBean0.getVCard();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      VCardBean vCardBean0 = new VCardBean();
      vCardBean0.setFirstName("Wzc]&(I#$j]<C0<+c4");
      String string0 = vCardBean0.getVCard();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      VCardBean vCardBean0 = new VCardBean();
      vCardBean0.setVCard("begin:vcard");
      String string0 = vCardBean0.getVCard();
      assertEquals("begin:vcard", string0);
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      VCardBean vCardBean0 = new VCardBean();
      String string0 = vCardBean0.getOrganization();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      VCardBean vCardBean0 = new VCardBean();
      String string0 = vCardBean0.getTitle();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      VCardBean vCardBean0 = new VCardBean();
      String string0 = vCardBean0.getEmail();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      VCardBean vCardBean0 = new VCardBean();
      String string0 = vCardBean0.getLastName();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      VCardBean vCardBean0 = new VCardBean();
      String string0 = vCardBean0.getFax();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      VCardBean vCardBean0 = new VCardBean();
      String string0 = vCardBean0.getFormattedName();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      VCardBean vCardBean0 = new VCardBean();
      String string0 = vCardBean0.getMiddleName();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      VCardBean vCardBean0 = new VCardBean();
      String string0 = vCardBean0.getFirstName();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      VCardBean vCardBean0 = new VCardBean();
      String string0 = vCardBean0.getPhone();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      VCardBean vCardBean0 = new VCardBean();
      vCardBean0.setVCard("BEGIN:VCARD\nFN:S-?5xc S-?5xc S-?5xc\nN:S-?5xc;S-?5xc;S-?5xc;\nTITLE:S-?5xc\nORG:S-?5xc\nEMAIL;TYPE=INTERNET:\nTEL;TYPE=VOICE:S-?5xc\nTEL;TYPE=FAX:S-?5xc\nEND:VCARD");
      assertEquals("S-?5xc", vCardBean0.getPhone());
      assertEquals("S-?5xc", vCardBean0.getOrganization());
  }
}
