/*
 * This file was automatically generated by EvoSuite
 * Tue Jan 16 19:32:45 GMT 2024
 */


import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class VCardBean_ESTest extends VCardBean_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      VCardBean vCardBean0 = new VCardBean();
      String string0 = vCardBean0.toString();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      VCardBean vCardBean0 = new VCardBean();
      vCardBean0.setVCard("Y.w1:;3H$@7");
      String string0 = vCardBean0.toString();
      assertEquals("Y.w1:;3H$@7", string0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      VCardBean vCardBean0 = new VCardBean();
      vCardBean0.setVCard("");
      String string0 = vCardBean0.toString();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      VCardBean vCardBean0 = new VCardBean();
      vCardBean0.setVCard("BEGIN:VCARDEMAIL;TYPE=INTERNET:");
      boolean boolean0 = vCardBean0.isValidVCard();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      VCardBean vCardBean0 = new VCardBean();
      boolean boolean0 = vCardBean0.isValidVCard();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      VCardBean vCardBean0 = new VCardBean();
      String string0 = vCardBean0.getVCard();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      VCardBean vCardBean0 = new VCardBean();
      vCardBean0.setVCard("BEGIN:VCARDEMAIL;TYPE=INTERNET:");
      String string0 = vCardBean0.getVCard();
      assertEquals("BEGIN:VCARDEMAIL;TYPE=INTERNET:", string0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      VCardBean vCardBean0 = new VCardBean();
      vCardBean0.setVCard("");
      String string0 = vCardBean0.getVCard();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      VCardBean vCardBean0 = new VCardBean();
      String string0 = vCardBean0.getTitle();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      VCardBean vCardBean0 = new VCardBean();
      vCardBean0.setTitle("r[M`AD7]zPA*8_h");
      String string0 = vCardBean0.getTitle();
      assertEquals("r[M`AD7]zPA*8_h", string0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      VCardBean vCardBean0 = new VCardBean();
      vCardBean0.setTitle("");
      String string0 = vCardBean0.getTitle();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      VCardBean vCardBean0 = new VCardBean();
      String string0 = vCardBean0.getPhone();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      VCardBean vCardBean0 = new VCardBean();
      vCardBean0.setPhone("&`Z9#{L1[%I");
      String string0 = vCardBean0.getPhone();
      assertEquals("&`Z9#{L1[%I", string0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      VCardBean vCardBean0 = new VCardBean();
      vCardBean0.setPhone("");
      String string0 = vCardBean0.getPhone();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      VCardBean vCardBean0 = new VCardBean();
      String string0 = vCardBean0.getOrganization();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      VCardBean vCardBean0 = new VCardBean();
      vCardBean0.setOrganization("tqEC5vC*j");
      String string0 = vCardBean0.getOrganization();
      assertEquals("tqEC5vC*j", string0);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      VCardBean vCardBean0 = new VCardBean();
      vCardBean0.setOrganization("");
      String string0 = vCardBean0.getOrganization();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      VCardBean vCardBean0 = new VCardBean();
      String string0 = vCardBean0.getMiddleName();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      VCardBean vCardBean0 = new VCardBean();
      vCardBean0.setMiddleName("fn");
      String string0 = vCardBean0.getMiddleName();
      assertEquals("fn", string0);
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      VCardBean vCardBean0 = new VCardBean();
      vCardBean0.setMiddleName("");
      String string0 = vCardBean0.getMiddleName();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      VCardBean vCardBean0 = new VCardBean();
      String string0 = vCardBean0.getLastName();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      VCardBean vCardBean0 = new VCardBean();
      vCardBean0.setLastName("xw72Mp/Q >#pL!bQ-aL");
      String string0 = vCardBean0.getLastName();
      assertEquals("xw72Mp/Q >#pL!bQ-aL", string0);
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      VCardBean vCardBean0 = new VCardBean();
      vCardBean0.setLastName("");
      String string0 = vCardBean0.getLastName();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      VCardBean vCardBean0 = new VCardBean();
      String string0 = vCardBean0.getFormattedName();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      VCardBean vCardBean0 = new VCardBean();
      vCardBean0.setFormattedName("/AdO\u0004,");
      String string0 = vCardBean0.getFormattedName();
      assertEquals("/AdO\u0004,", string0);
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      VCardBean vCardBean0 = new VCardBean();
      vCardBean0.setFormattedName("");
      String string0 = vCardBean0.getFormattedName();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      VCardBean vCardBean0 = new VCardBean();
      String string0 = vCardBean0.getFirstName();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      VCardBean vCardBean0 = new VCardBean();
      vCardBean0.setFirstName("n");
      String string0 = vCardBean0.getFirstName();
      assertEquals("n", string0);
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      VCardBean vCardBean0 = new VCardBean();
      vCardBean0.setFirstName("");
      String string0 = vCardBean0.getFirstName();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      VCardBean vCardBean0 = new VCardBean();
      String string0 = vCardBean0.getFax();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      VCardBean vCardBean0 = new VCardBean();
      vCardBean0.setFax("eNpRF({KUD{Hhq.");
      String string0 = vCardBean0.getFax();
      assertEquals("eNpRF({KUD{Hhq.", string0);
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      VCardBean vCardBean0 = new VCardBean();
      vCardBean0.setFax("");
      String string0 = vCardBean0.getFax();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      VCardBean vCardBean0 = new VCardBean();
      String string0 = vCardBean0.getEmail();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      VCardBean vCardBean0 = new VCardBean();
      vCardBean0.setEmail("K\"~2Yq@XTx,PP6");
      String string0 = vCardBean0.getEmail();
      assertEquals("K\"~2Yq@XTx,PP6", string0);
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      VCardBean vCardBean0 = new VCardBean();
      vCardBean0.setEmail("");
      String string0 = vCardBean0.getEmail();
      assertEquals("", string0);
  }
}
