/*
 * This file was automatically generated by EvoSuite
 * Mon Jan 15 14:41:20 GMT 2024
 */


import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Calcolatrice_ESTest extends Calcolatrice_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Calcolatrice calcolatrice0 = new Calcolatrice();
      int int0 = calcolatrice0.divide(1, 4797);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Calcolatrice calcolatrice0 = new Calcolatrice();
      int int0 = calcolatrice0.divide(1, (-1));
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Calcolatrice calcolatrice0 = new Calcolatrice();
      // Undeclared exception!
      try { 
        calcolatrice0.divide((-1834), 0);
        fail("Expecting exception: ArithmeticException");
      
      } catch(ArithmeticException e) {
         //
         // Cannot divide by zero
         //
         verifyException("Calcolatrice", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Calcolatrice calcolatrice0 = new Calcolatrice();
      int int0 = calcolatrice0.divide((-1386), (-1386));
      assertEquals(1, int0);
  }
}
